version: "3.9"

services:
  app:
    tty: true
    container_name: app
    image: paper-summerizer-app:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - api
    networks:
      - backend

  api:
    tty: true
    container_name: api
    image: paper-summerizer-api:latest
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
